--- 
before_script: 
- gem install hoe-travis --no-rdoc --no-ri
- rake travis:before -t
after_script: 
- rake travis:after -t
script: rake
language: ruby
rvm: 
- 1.8.7
- 1.9.2
- 1.9.3
- 2.0.0
notifications: 
  email: 
  - caizhaoff@gmail.com
